In [1]:
import numpy as np

In [2]:
x = np.array([1, 2])
x.shape


(2,)

In [3]:
y = np.expand_dims(x, axis=0)
y


array([[1, 2]])

In [4]:
y.shape

(1, 2)

In [5]:
y = np.expand_dims(x, axis=1)
y

array([[1],
       [2]])

In [6]:
y.shape

(2, 1)

In [7]:
y = np.expand_dims(x, axis=(0, 1))
y


array([[[1, 2]]])

In [8]:
y.shape

(1, 1, 2)

In [9]:
y = np.expand_dims(x, axis=(2, 0))
y


array([[[1],
        [2]]])

In [10]:
y.shape

(1, 2, 1)

In [11]:
np.newaxis is None

True

In [12]:
y = x[np.newaxis, :]
y

array([[1, 2]])

In [13]:
y.shape

(1, 2)

In [14]:
y = x[None, :]
y

array([[1, 2]])