In [1]:
import numpy as np

In [2]:
x = np.array([1, 2])
x.shape


(2,)

In [3]:
y = np.expand_dims(x, axis=0)
y


array([[1, 2]])

In [4]:
y.shape

(1, 2)

In [5]:
y = np.expand_dims(x, axis=1)
y

array([[1],
       [2]])

In [6]:
y.shape

(2, 1)

In [7]:
y = np.expand_dims(x, axis=(0, 1))
y


array([[[1, 2]]])

In [8]:
y.shape

(1, 1, 2)

In [9]:
y = np.expand_dims(x, axis=(2, 0))
y


array([[[1],
        [2]]])

In [10]:
y.shape

(1, 2, 1)

In [11]:
np.newaxis is None

True

In [12]:
y = x[np.newaxis, :]
y

array([[1, 2]])

In [13]:
y.shape

(1, 2)

In [14]:
y = x[None, :]
y

array([[1, 2]])

In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.vstack((a, b))


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [17]:
a.shape

(3, 1)

In [18]:
b.shape

(3, 1)

In [20]:
np.vstack((a, b)).shape


(6, 1)

In [21]:
np.vstack([a]).shape


(3, 1)

In [22]:
a.shape

(3, 1)