In [1]:
import tensorflow as tf
import numpy as np

# 创建 Tensor

- 从 numpy, list 
- zeros, ones 方法
- fill 方法
- random
- constant

## 从 Numpy, list 创建

In [2]:
tf.convert_to_tensor(np.ones([2, 3])) # 2行3列，默认为 float64

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [3]:
tf.convert_to_tensor(np.zeros([2, 3])) # 2 行 3 列

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]])>

In [4]:
tf.convert_to_tensor([1, 2]) # 直接从 list 转换，类型和 list 一样

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [5]:
tf.convert_to_tensor([1, 2.]) # 因为有 float 值，此时类型为 float32

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [6]:
tf.convert_to_tensor([[1], [2.]]) # 两行一列

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

## zeros

In [7]:
tf.zeros([]) # 传入的参数为 shape，此时 shape 为空，表示标量

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [8]:
tf.zeros([1]) # 1维的向量，默认为 float32

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [9]:
tf.zeros([2, 2]) # 2 行 2 列

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [10]:
tf.zeros([2, 3, 3])

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

## zeros_like

In [11]:
a = tf.zeros([2, 3, 3])

In [12]:
tf.zeros_like(a) # 就是以和 a 相同的 shape 创建全部为 0 的 tensor

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [13]:
tf.zeros(a.shape) # 这个和 tf.zeros_like(a) 效果一样

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

## tf.ones

In [14]:
tf.ones(1) # 此时 shape 为 (1,)，即创建 1 维长度为 1 的 tensor

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [15]:
tf.ones([]) # 此时创建的等同于标量

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [16]:
tf.ones([2])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [17]:
tf.ones([2, 3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [18]:
tf.ones_like(a)

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

## fill

In [19]:
tf.fill([2, 2], 0)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]])>

In [20]:
tf.fill([2, 2], 0.)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [21]:
tf.fill([2, 2], 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]])>

In [22]:
tf.fill([2, 2], 9)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 9],
       [9, 9]])>

## normal

In [23]:
tf.random.normal([2, 2], mean=1, stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.7239852 , 1.4705689 ],
       [0.14141953, 2.1234195 ]], dtype=float32)>

In [24]:
tf.random.normal([2, 2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.5919194, -1.0863346],
       [ 0.9592807, -1.6967909]], dtype=float32)>

In [25]:
tf.random.truncated_normal([2, 2], mean=0, stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.34309438,  1.146455  ],
       [-0.04982517, -1.6060449 ]], dtype=float32)>

## uniform

In [26]:
tf.random.uniform([2, 2], minval=0, maxval=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5093099 , 0.6882236 ],
       [0.69041145, 0.33028662]], dtype=float32)>

In [27]:
tf.random.uniform([2, 2], minval=0, maxval=100)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[20.718134 , 15.262318 ],
       [82.72535  ,  7.2973013]], dtype=float32)>

## random permutation

In [28]:
idx = tf.range(10)
idx = tf.random.shuffle(idx) # 打乱顺序
idx

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 4, 5, 2, 9, 3, 6, 7, 0, 8])>

In [29]:
a = tf.random.normal([10, 784])  # 模拟10 张照片数据
b = tf.random.uniform([10], maxval=10, dtype=tf.int32) # 模拟输出
b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 7, 8, 1, 1, 7, 1, 9, 6, 2])>

In [30]:
a = tf.gather(a, idx) # 以 idx 从 a 中收集数据
a

<tf.Tensor: shape=(10, 784), dtype=float32, numpy=
array([[-0.05171316, -0.93531907,  0.83632463, ...,  0.5874435 ,
        -0.7310395 ,  0.76639915],
       [-0.5607087 ,  2.2232518 ,  0.91765773, ..., -0.18367405,
         0.0469209 , -1.1900312 ],
       [ 0.8970636 , -1.234274  , -0.59756094, ...,  1.5703455 ,
         0.19690019,  0.25312263],
       ...,
       [ 0.32218987,  1.4969801 , -0.45277464, ..., -1.1743239 ,
         0.19129474,  1.340405  ],
       [-2.030395  , -0.02167227, -0.24810445, ...,  0.5577358 ,
         0.9682151 , -0.6652755 ],
       [-1.2119052 ,  2.1797738 , -1.441932  , ...,  0.61153835,
         0.04533297, -0.47672558]], dtype=float32)>

In [31]:
b = tf.gather(b, idx)
b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([7, 1, 7, 8, 2, 1, 1, 9, 1, 6])>

## tf.constant

In [32]:
tf.constant(1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [33]:
tf.constant([1])

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1])>

In [34]:
tf.constant([1, 2.])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [35]:
tf.constant([[1, 2.], [3.]]) # 维度不一致报错

ValueError: Can't convert non-rectangular Python sequence to Tensor.

## loss

In [36]:
out = tf.random.uniform([4, 10]) # 4 张照片的预测结果

In [37]:
out

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[7.00363159e-01, 1.52490377e-01, 3.23032498e-01, 2.05719948e-01,
        3.60240936e-02, 1.34951234e-01, 6.79450035e-02, 2.98813939e-01,
        8.81114006e-02, 1.64361715e-01],
       [2.52164602e-01, 3.01935196e-01, 7.08177805e-01, 9.92557049e-01,
        3.02463412e-01, 2.12479353e-01, 7.70157576e-01, 5.40997148e-01,
        1.19743705e-01, 2.59249568e-01],
       [1.63296938e-01, 8.67923498e-01, 8.43779683e-01, 6.79350853e-01,
        6.33765221e-01, 6.13778710e-01, 9.85445738e-01, 3.51905823e-04,
        4.31298375e-01, 9.21976089e-01],
       [5.08470178e-01, 3.70819569e-01, 6.20276451e-01, 7.46981025e-01,
        8.22409391e-02, 7.45405197e-01, 4.78370905e-01, 8.40433240e-01,
        1.11093879e-01, 5.77461958e-01]], dtype=float32)>