In [1]:
import tensorflow as tf

In [2]:
tf.constant(1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [3]:
tf.constant(1.)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [4]:
tf.constant(2.2, dtype=tf.int32)

TypeError: Cannot convert 2.2 to EagerTensor of dtype int32

In [5]:
tf.constant(2., dtype=tf.double)

<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

In [6]:
tf.constant([True, False])

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [7]:
tf.constant('hello,world.')

<tf.Tensor: shape=(), dtype=string, numpy=b'hello,world.'>

In [9]:
# 创建一个 CPU tensor
with tf.device("cpu"):
    a = tf.constant([1])

In [10]:
# 创建一个 GPU tensor
with tf.device("gpu"): # 没有 GPU 貌似也不会报错
    b = tf.range(4)

In [11]:
a.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [12]:
b.device # 不会报错，而是自动转到了 CPU

'/job:localhost/replica:0/task:0/device:CPU:0'

In [13]:
aa = a.gpu() # 从 CPU 转义到 GPU，此时没有 GPU 就会报错

Instructions for updating:
Use tf.identity instead.


RuntimeError: GPU:0 unknown device.

In [14]:
bb = b.cpu()

Instructions for updating:
Use tf.identity instead.


In [15]:
bb.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [16]:
b.numpy() # 转换为 numpy 数组类型

array([0, 1, 2, 3])

In [17]:
b.ndim # 查看有几个维度

1

In [18]:
tf.rank(b) # rank 和 ndim 的功能类似，但是返回 tensor，一般用 ndim 即可

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [19]:
tf.rank(tf.ones([3, 4, 2])) # 此时维度为3

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [20]:
b.name # 已经不推荐使用 name,这是 tensorflow 1.x 遗留属性

AttributeError: Tensor.name is meaningless when eager execution is enabled.

# 检查 tensor 类型

In [21]:
a = tf.constant([1.])

In [22]:
b = tf.constant([True, False])

In [23]:
c = tf.constant('hello,world.')

In [24]:
import numpy as np
d = np.arange(4)

In [25]:
isinstance(a, tf.Tensor) # 这个没有问题

True

In [26]:
tf.is_tensor(b)

True

In [27]:
tf.is_tensor(d) # 推荐使用这种方式，而不是 isinstance()

False

In [28]:
a.dtype, b.dtype, c.dtype

(tf.float32, tf.bool, tf.string)

In [29]:
a.dtype == tf.float32 # 通过 dtype 判断类型

True

# 类型转换

In [31]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [32]:
a.dtype # 此时 a 的类型为 int32

dtype('int32')

In [35]:
aa = tf.convert_to_tensor(a) # 可以看到，tensor 类型和 numpy 树类型一样
aa

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [36]:
tf.cast(aa, dtype=tf.float32) # 转换为其它类型

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

In [38]:
aaa = tf.cast(aa, dtype=tf.float64)
aaa

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([0., 1., 2., 3., 4.])>

In [39]:
tf.cast(aaa, dtype=tf.int32) # 又转换回来了

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

# bool int 转换

In [41]:
b = tf.constant([0, 1])

In [42]:
tf.cast(b, dtype=tf.bool) # 0 转换为 False, 1 转换为 True

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False,  True])>

In [43]:
bb = tf.cast(b, dtype=tf.bool) # 转换为 bool
tf.cast(bb, tf.int32) # 又转换回 int32

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1])>

# tf.Variable

专门为神经网络参数设置的类型，这类变量会自动保留梯度信息

In [45]:
a = tf.range(5)
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [46]:
b = tf.Variable(a)

In [47]:
b.dtype

tf.int32

In [48]:
b.name # 也不推荐用了

'Variable:0'

In [49]:
b.trainable # 表示需要对 b 求导，需要保留其梯度信息

True

In [50]:
isinstance(b, tf.Tensor)

False

In [51]:
isinstance(b, tf.Variable)

True

In [52]:
tf.is_tensor(b) # 推荐使用这种方式，对继承类型，isinstance 就不对

True

In [53]:
b.numpy() # 转换为 numpy

array([0, 1, 2, 3, 4])