# 索引和切片

In [2]:
import tensorflow as tf

In [3]:
a = tf.ones([1, 5, 5, 3])

## 传统索引方式

In [4]:
a[0][0][0]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [5]:
a[0][0][0][2]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

## NumPy 样式索引

In [6]:
a = tf.random.normal([4, 28, 28, 3]) # 想想为4张图片

In [7]:
a[1].shape # 第2张图片

TensorShape([28, 28, 3])

In [8]:
a[1, 2].shape # 图片2的第3行像素

TensorShape([28, 3])

In [9]:
a[1, 2, 3].shape # 图片2的第3行，第4列像素

TensorShape([3])

In [10]:
a[1, 2, 3, 2].shape # 像素的 B 值

TensorShape([])

## start:end 切片

In [11]:
a = tf.range(10)

In [12]:
a

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [13]:
a[-1:] # -1 到结尾，即取最后一个

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([9])>

In [14]:
a[-2:] # -2 到结尾，即最后两个

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 9])>

In [15]:
a[:2] # 开头到第3个，即前两个

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1])>

In [16]:
a[:-1] # 开头到最后一个，即去掉最后一个

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [17]:
a = tf.random.normal([4, 28, 28, 3]) # 想象为4张图片

In [18]:
a.shape

TensorShape([4, 28, 28, 3])

In [19]:
a[0].shape # 第1张图片

TensorShape([28, 28, 3])

In [20]:
a[0,:,:,:].shape # 还是第1张图片

TensorShape([28, 28, 3])

In [21]:
a[0,1,:,:].shape # 第1张图片的第2行

TensorShape([28, 3])

In [22]:
a[:,:,:,0].shape # 所有图片的 R 值

TensorShape([4, 28, 28])

In [23]:
a[:,:,:,2].shape # 所有图片的 B 值

TensorShape([4, 28, 28])

In [24]:
a[:,0,:,:].shape # 所有图片的第一行 [4,28,3]

TensorShape([4, 28, 3])

## 跳跃取值

In [25]:
a.shape

TensorShape([4, 28, 28, 3])

In [26]:
a[0:2,:,:,:].shape # 前2张图片 [2, 28, 28, 3]

TensorShape([2, 28, 28, 3])

In [27]:
a[:,0:28:2, 0:28:2,:].shape # 每个图片隔行取像素 [4,14,14,3]

TensorShape([4, 14, 14, 3])

In [28]:
a[:,:14,:14,:].shape # 取图片的左上角1/4

TensorShape([4, 14, 14, 3])

In [29]:
a[:,14:,14:,:].shape # 取右下角 1/4

TensorShape([4, 14, 14, 3])

In [30]:
a[:,::2,::2,:].shape # 隔行取像素

TensorShape([4, 14, 14, 3])

## -1 倒序

In [31]:
a = tf.range(4)
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3])>

In [32]:
a[::-1]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 2, 1, 0])>

In [33]:
a[::-2] # 倒着间隔取

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 1])>

In [34]:
a[2::-2] # 从第3个开始倒着间隔取

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 0])>

### ... 省略语法

In [35]:
a = tf.random.normal([2, 4, 28, 28, 3])

In [36]:
a[0].shape

TensorShape([4, 28, 28, 3])

In [37]:
a[0,:,:,:,:].shape # 省略号有点多

TensorShape([4, 28, 28, 3])

In [38]:
a[0,...].shape # 简洁许多

TensorShape([4, 28, 28, 3])

In [39]:
a[:,:,:,:,0].shape

TensorShape([2, 4, 28, 28])

In [40]:
a[...,0].shape

TensorShape([2, 4, 28, 28])

In [41]:
a[0,...,2].shape

TensorShape([4, 28, 28])

## tf.gather

假设有如下学生成绩数据：[classes, students, subjects]

In [42]:
data = tf.random.normal([4, 35, 8])

In [44]:
tf.gather(data, axis=0, indices=[2, 3]).shape # 选择3，4两个班级所有学生 [2, 35, 8]

TensorShape([2, 35, 8])

In [45]:
data[2:4].shape # 同上

TensorShape([2, 35, 8])

In [46]:
tf.gather(data, axis=0, indices=[2, 1, 3, 0]).shape # 打乱顺序 [4, 35, 8]

TensorShape([4, 35, 8])

In [47]:
tf.gather(data, axis=1, indices=[2, 3, 7, 9, 16]).shape # axis=1 表示学生，从每个班级的 35 个学生中选择对应编号的 5 个学生 [4, 5, 8]

TensorShape([4, 5, 8])

In [48]:
tf.gather(data, axis=2, indices=[2, 3, 7]).shape # axis=2 表示成绩，选择所有班级，所有学生的 [2, 3, 7] 编号对应的成绩 [4, 35, 3]

TensorShape([4, 35, 3])

## tf.gather_nd

可以针对多个维度提取数据

In [49]:
a = tf.random.normal([4, 35, 8])

In [50]:
tf.gather_nd(a, [0]).shape # 收集班级 1  的数据 [35,8]

TensorShape([35, 8])

In [51]:
tf.gather_nd(a, [0,1]).shape # 收集班级 1 学生 2的数据 [8]

TensorShape([8])

In [52]:
tf.gather_nd(a, [0,1,2]).shape # 标量

TensorShape([])

In [53]:
tf.gather_nd(a, [[0, 1, 2]]).shape # 收集 a[0,1,2] 并转换为向量

TensorShape([1])

In [54]:
tf.gather_nd(a, [[0,0], [1,1]]).shape # 收集班级1学生1和班级2学生2的成绩 [2,8]

TensorShape([2, 8])

In [55]:
tf.gather_nd(a, [[[0,0,0],[1,1,1],[2,2,2]]]).shape # 收集班级1学生1成绩1，班级2学生2成绩2，班级3学生3成绩3，组成数组，该数组再放入一个数组，所以是 [1,3]

TensorShape([1, 3])

## boolean_mask

In [56]:
a = tf.random.normal([4, 28, 28, 3])

In [57]:
tf.boolean_mask(a, mask=[True, True, False, False]).shape # 前两个图片，[2,28,28,3]

TensorShape([2, 28, 28, 3])

In [58]:
tf.boolean_mask(a, mask=[True, True, False], axis=3).shape # 提取像素 RG [4, 28, 28, 2]

TensorShape([4, 28, 28, 2])

In [59]:
a = tf.ones([2,3,4])

In [60]:
tf.boolean_mask(a, mask=[[True,False,False],[False,True,True]]) # 

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>